### ISSUE TITLE
Parsing failed on GitHub in 01-introduction.md

### ISSUE THREAD

**Issue by 515hikaru** [Songmu/ghq-handbook#2]
In [01-introduction.md](https://github.com/Songmu/ghq-handbook/blob/master/ja/01-introduction.md) 's last section, the display was strange.

Below is a screenshot.

![](https://user-images.githubusercontent.com/34483340/71780053-1d20a280-3001-11ea-8db1-e3923b885847.png)

I did not know how to fix it, so I am reporting.

By the way, the PDF did not have this problem.

**Comment by Songmu** [comment]
ありがとうございます。これはMarkdownの自動リンクが悪さしていたようです。 `)` がURLに含められる文字列なので、 ```https://github.com/motemen/ghq)に対して`go``` までがURLとみなされていたことでbacktickの入れ子がおかしくなったのが原因のようです。

a2547bd で修正しました。ありがとうございます！
